# Generated by Django 3.2.12 on 2022-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('tema', models.CharField(max_length=140)),
                ('texto', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
